### ISSUE TITLE
Remove EntityFramework Dependency from Core library

### ISSUE THREAD

**Issue by enisn** [furkandeveloper/EasyProfiler#68]
`EasyProfiler.Mongo` package brings `EntityFrameworkCore` packages with it. Because `EasyProfiler.Core` has dependency to `EntityFrameworkCore`

**Hierarchy must be:**

- EasyProfiler.Core _(No EntityFramework dependency here ❌)_
  - EasyProfiler.Mongo
  - EasyProfiler.EntityFrameworkCore _(EntityFramework dependency ✔)_
     -  EasyProfiler.EntityFrameworkCore.MariaDb
     - EasyProfiler.EntityFrameworkCore.MySql
     - EasyProfiler.EntityFrameworkCore.PostgreSQL
     - ...

**Comment by furkandeveloper** [comment]
Your PR I am waiting. @enisn 🎉

**Comment by furkandeveloper** [comment]
Yes, you right @enisn. 
This repository firstly supported Relational Database Techlonogies. Mongo after supported.
See [Release Notes](https://github.com/furkandeveloper/EasyProfiler/releases)
